version: 2
project_name: gosync
dist: build
before:
  hooks:
    - go mod tidy
    - node sdk/js/build.mjs
builds:
  - id: server
    main: ./cmd/gosync-server
    binary: gosync-server
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
release:
  extra_files:
    - glob: sdk/js/gosync.wasm
    - glob: sdk/js/wasm_exec.js
    - glob: sdk/js/gosync.js
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
